CREATE SCHEMA IF NOT EXISTS samply;
SET search_path TO samply,public;

CREATE TYPE ACTION_TYPE AS ENUM (
  'AT_NEW_PROJECT',
  'AT_PROJECT_ENDING_TODAY',
  'AT_PROJECT_ENDING_SOON',
  'AT_PROJECT_ARCHIVED',
  'AT_PROJECT_ACTIVATED',
  'AT_PROJECT_OPENED',
  'AT_PROJECT_REJECTED',
  'AT_PROJECT_CALLBACK_SENT',
  'AT_PROJECT_CALLBACK_RECEIVED',
  'AT_USER_MESSAGE',
  'AT_REMINDER',
  'AT_REMINDER_EXTERNAL',
  'AT_INQUIRY_EDITED'
);

CREATE TYPE INQUIRY_STATUS AS ENUM (
  'IS_DRAFT',
  'IS_RELEASED',
  'IS_OUTDATED'
);

CREATE TYPE PROJECT_STATUS AS ENUM (
  'PS_NEW',
  'PS_OPEN_MOREINFO_NEEDED',
  'PS_OPEN_MOREINFO_PROVIDED',
  'PS_OPEN_DISTRIBUTION',
  'PS_ACTIVE',
  'PS_CLOSED',
  'PS_REJECTED'
);

CREATE TYPE DOCUMENT_TYPE AS ENUM (
  'DT_EXPOSE',
  'DT_VOTE',
  'DT_REPORT_PROGRESS',
  'DT_REPORT_FINAL',
  'DT_EXPERT_ASSESSMENT',
  'DT_OTHER'
);

COMMENT ON SCHEMA samply IS 'schema used for samply share broker';