/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables;


import de.samply.share.broker.model.db.Keys;
import de.samply.share.broker.model.db.Samply;
import de.samply.share.broker.model.db.tables.records.BankSiteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankSite extends TableImpl<BankSiteRecord> {

    private static final long serialVersionUID = -29310037;

    /**
     * The reference instance of <code>samply.bank_site</code>
     */
    public static final BankSite BANK_SITE = new BankSite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BankSiteRecord> getRecordType() {
        return BankSiteRecord.class;
    }

    /**
     * The column <code>samply.bank_site.bank_id</code>.
     */
    public final TableField<BankSiteRecord, Integer> BANK_ID = createField("bank_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.bank_site.site_id</code>.
     */
    public final TableField<BankSiteRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.bank_site.approved</code>.
     */
    public final TableField<BankSiteRecord, Boolean> APPROVED = createField("approved", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>samply.bank_site</code> table reference
     */
    public BankSite() {
        this("bank_site", null);
    }

    /**
     * Create an aliased <code>samply.bank_site</code> table reference
     */
    public BankSite(String alias) {
        this(alias, BANK_SITE);
    }

    private BankSite(String alias, Table<BankSiteRecord> aliased) {
        this(alias, aliased, null);
    }

    private BankSite(String alias, Table<BankSiteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BankSiteRecord> getPrimaryKey() {
        return Keys.BANK_SITE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BankSiteRecord>> getKeys() {
        return Arrays.<UniqueKey<BankSiteRecord>>asList(Keys.BANK_SITE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BankSiteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BankSiteRecord, ?>>asList(Keys.BANK_SITE__BANK_SITE_BANK_ID_FKEY, Keys.BANK_SITE__BANK_SITE_SITE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankSite as(String alias) {
        return new BankSite(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BankSite rename(String name) {
        return new BankSite(name, null);
    }
}
