/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables;


import de.samply.share.broker.model.db.Keys;
import de.samply.share.broker.model.db.Samply;
import de.samply.share.broker.model.db.tables.records.EmailSiteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailSite extends TableImpl<EmailSiteRecord> {

    private static final long serialVersionUID = 687026935;

    /**
     * The reference instance of <code>samply.email_site</code>
     */
    public static final EmailSite EMAIL_SITE = new EmailSite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmailSiteRecord> getRecordType() {
        return EmailSiteRecord.class;
    }

    /**
     * The column <code>samply.email_site.id</code>.
     */
    public final TableField<EmailSiteRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('samply.email_site_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>samply.email_site.email</code>.
     */
    public final TableField<EmailSiteRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>samply.email_site.site</code>.
     */
    public final TableField<EmailSiteRecord, Integer> SITE = createField("site", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>samply.email_site</code> table reference
     */
    public EmailSite() {
        this("email_site", null);
    }

    /**
     * Create an aliased <code>samply.email_site</code> table reference
     */
    public EmailSite(String alias) {
        this(alias, EMAIL_SITE);
    }

    private EmailSite(String alias, Table<EmailSiteRecord> aliased) {
        this(alias, aliased, null);
    }

    private EmailSite(String alias, Table<EmailSiteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EmailSiteRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EMAIL_SITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EmailSiteRecord> getPrimaryKey() {
        return Keys.EMAIL_SITE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EmailSiteRecord>> getKeys() {
        return Arrays.<UniqueKey<EmailSiteRecord>>asList(Keys.EMAIL_SITE_PKEY, Keys.EMAIL_SITE_EMAIL_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<EmailSiteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EmailSiteRecord, ?>>asList(Keys.EMAIL_SITE__EMAIL_SITE_SITE_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailSite as(String alias) {
        return new EmailSite(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmailSite rename(String name) {
        return new EmailSite(name, null);
    }
}
