/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables;


import de.samply.share.broker.model.db.Keys;
import de.samply.share.broker.model.db.Samply;
import de.samply.share.broker.model.db.tables.records.InquirySiteRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquirySite extends TableImpl<InquirySiteRecord> {

    private static final long serialVersionUID = 911789660;

    /**
     * The reference instance of <code>samply.inquiry_site</code>
     */
    public static final InquirySite INQUIRY_SITE = new InquirySite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InquirySiteRecord> getRecordType() {
        return InquirySiteRecord.class;
    }

    /**
     * The column <code>samply.inquiry_site.inquiry_id</code>.
     */
    public final TableField<InquirySiteRecord, Integer> INQUIRY_ID = createField("inquiry_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.inquiry_site.site_id</code>.
     */
    public final TableField<InquirySiteRecord, Integer> SITE_ID = createField("site_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.inquiry_site.retrieved_at</code>.
     */
    public final TableField<InquirySiteRecord, Timestamp> RETRIEVED_AT = createField("retrieved_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>samply.inquiry_site</code> table reference
     */
    public InquirySite() {
        this("inquiry_site", null);
    }

    /**
     * Create an aliased <code>samply.inquiry_site</code> table reference
     */
    public InquirySite(String alias) {
        this(alias, INQUIRY_SITE);
    }

    private InquirySite(String alias, Table<InquirySiteRecord> aliased) {
        this(alias, aliased, null);
    }

    private InquirySite(String alias, Table<InquirySiteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InquirySiteRecord> getPrimaryKey() {
        return Keys.INQUIRY_SITE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InquirySiteRecord>> getKeys() {
        return Arrays.<UniqueKey<InquirySiteRecord>>asList(Keys.INQUIRY_SITE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InquirySiteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InquirySiteRecord, ?>>asList(Keys.INQUIRY_SITE__INQUIRY_SITE_INQUIRY_ID_FKEY, Keys.INQUIRY_SITE__INQUIRY_SITE_SITE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquirySite as(String alias) {
        return new InquirySite(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InquirySite rename(String name) {
        return new InquirySite(name, null);
    }
}
