/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.enums;


import de.samply.share.broker.model.db.Samply;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ProjectStatus implements EnumType {

    PS_NEW("PS_NEW"),

    PS_OPEN_MOREINFO_NEEDED("PS_OPEN_MOREINFO_NEEDED"),

    PS_OPEN_MOREINFO_PROVIDED("PS_OPEN_MOREINFO_PROVIDED"),

    PS_OPEN_DISTRIBUTION("PS_OPEN_DISTRIBUTION"),

    PS_ACTIVE("PS_ACTIVE"),

    PS_CLOSED("PS_CLOSED"),

    PS_REJECTED("PS_REJECTED");

    private final String literal;

    private ProjectStatus(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "project_status";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
