/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.enums.ActionType;
import de.samply.share.broker.model.db.tables.Action;

import java.sql.Date;
import java.sql.Time;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActionRecord extends UpdatableRecordImpl<ActionRecord> implements Record8<Integer, ActionType, Date, Time, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1277865608;

    /**
     * Setter for <code>samply.action.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.action.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.action.type</code>.
     */
    public void setType(ActionType value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.action.type</code>.
     */
    public ActionType getType() {
        return (ActionType) get(1);
    }

    /**
     * Setter for <code>samply.action.date</code>.
     */
    public void setDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.action.date</code>.
     */
    public Date getDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>samply.action.time</code>.
     */
    public void setTime(Time value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.action.time</code>.
     */
    public Time getTime() {
        return (Time) get(3);
    }

    /**
     * Setter for <code>samply.action.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>samply.action.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>samply.action.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>samply.action.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>samply.action.message</code>.
     */
    public void setMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>samply.action.message</code>.
     */
    public String getMessage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>samply.action.icon</code>.
     */
    public void setIcon(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>samply.action.icon</code>.
     */
    public String getIcon() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, ActionType, Date, Time, Integer, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, ActionType, Date, Time, Integer, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Action.ACTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActionType> field2() {
        return Action.ACTION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Action.ACTION.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field4() {
        return Action.ACTION.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Action.ACTION.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Action.ACTION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Action.ACTION.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Action.ACTION.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionType value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value2(ActionType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value3(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value4(Time value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value5(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value7(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord value8(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActionRecord values(Integer value1, ActionType value2, Date value3, Time value4, Integer value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActionRecord
     */
    public ActionRecord() {
        super(Action.ACTION);
    }

    /**
     * Create a detached, initialised ActionRecord
     */
    public ActionRecord(Integer id, ActionType type, Date date, Time time, Integer projectId, Integer userId, String message, String icon) {
        super(Action.ACTION);

        set(0, id);
        set(1, type);
        set(2, date);
        set(3, time);
        set(4, projectId);
        set(5, userId);
        set(6, message);
        set(7, icon);
    }
}
