/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.enums.InquiryStatus;
import de.samply.share.broker.model.db.tables.Inquiry;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryRecord extends UpdatableRecordImpl<InquiryRecord> implements Record13<Integer, Integer, String, String, Timestamp, Date, Integer, Boolean, String, String, InquiryStatus, Integer, String> {

    private static final long serialVersionUID = 156119350;

    /**
     * Setter for <code>samply.inquiry.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>samply.inquiry.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>samply.inquiry.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>samply.inquiry.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>samply.inquiry.expires</code>.
     */
    public void setExpires(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>samply.inquiry.expires</code>.
     */
    public Date getExpires() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>samply.inquiry.author_id</code>.
     */
    public void setAuthorId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>samply.inquiry.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>samply.inquiry.archived</code>.
     */
    public void setArchived(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>samply.inquiry.archived</code>.
     */
    public Boolean getArchived() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>samply.inquiry.criteria</code>.
     */
    public void setCriteria(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>samply.inquiry.criteria</code>.
     */
    public String getCriteria() {
        return (String) get(8);
    }

    /**
     * Setter for <code>samply.inquiry.viewfields</code>.
     */
    public void setViewfields(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>samply.inquiry.viewfields</code>.
     */
    public String getViewfields() {
        return (String) get(9);
    }

    /**
     * Setter for <code>samply.inquiry.status</code>.
     */
    public void setStatus(InquiryStatus value) {
        set(10, value);
    }

    /**
     * Getter for <code>samply.inquiry.status</code>.
     */
    public InquiryStatus getStatus() {
        return (InquiryStatus) get(10);
    }

    /**
     * Setter for <code>samply.inquiry.revision</code>.
     */
    public void setRevision(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>samply.inquiry.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>samply.inquiry.result_type</code>.
     */
    public void setResultType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>samply.inquiry.result_type</code>.
     */
    public String getResultType() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, Timestamp, Date, Integer, Boolean, String, String, InquiryStatus, Integer, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, String, String, Timestamp, Date, Integer, Boolean, String, String, InquiryStatus, Integer, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Inquiry.INQUIRY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Inquiry.INQUIRY.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Inquiry.INQUIRY.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inquiry.INQUIRY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Inquiry.INQUIRY.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Inquiry.INQUIRY.EXPIRES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Inquiry.INQUIRY.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Inquiry.INQUIRY.ARCHIVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Inquiry.INQUIRY.CRITERIA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Inquiry.INQUIRY.VIEWFIELDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InquiryStatus> field11() {
        return Inquiry.INQUIRY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Inquiry.INQUIRY.REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Inquiry.INQUIRY.RESULT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getExpires();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getArchived();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCriteria();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getViewfields();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryStatus value11() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getResultType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value2(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value3(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value5(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value6(Date value) {
        setExpires(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value7(Integer value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value8(Boolean value) {
        setArchived(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value9(String value) {
        setCriteria(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value10(String value) {
        setViewfields(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value11(InquiryStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value12(Integer value) {
        setRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value13(String value) {
        setResultType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5, Date value6, Integer value7, Boolean value8, String value9, String value10, InquiryStatus value11, Integer value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryRecord
     */
    public InquiryRecord() {
        super(Inquiry.INQUIRY);
    }

    /**
     * Create a detached, initialised InquiryRecord
     */
    public InquiryRecord(Integer id, Integer projectId, String label, String description, Timestamp created, Date expires, Integer authorId, Boolean archived, String criteria, String viewfields, InquiryStatus status, Integer revision, String resultType) {
        super(Inquiry.INQUIRY);

        set(0, id);
        set(1, projectId);
        set(2, label);
        set(3, description);
        set(4, created);
        set(5, expires);
        set(6, authorId);
        set(7, archived);
        set(8, criteria);
        set(9, viewfields);
        set(10, status);
        set(11, revision);
        set(12, resultType);
    }
}
