/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.tables.InquirySite;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquirySiteRecord extends UpdatableRecordImpl<InquirySiteRecord> implements Record3<Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1533637387;

    /**
     * Setter for <code>samply.inquiry_site.inquiry_id</code>.
     */
    public void setInquiryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_site.inquiry_id</code>.
     */
    public Integer getInquiryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_site.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_site.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_site.retrieved_at</code>.
     */
    public void setRetrievedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_site.retrieved_at</code>.
     */
    public Timestamp getRetrievedAt() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquirySite.INQUIRY_SITE.INQUIRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquirySite.INQUIRY_SITE.SITE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return InquirySite.INQUIRY_SITE.RETRIEVED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInquiryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSiteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getRetrievedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquirySiteRecord value1(Integer value) {
        setInquiryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquirySiteRecord value2(Integer value) {
        setSiteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquirySiteRecord value3(Timestamp value) {
        setRetrievedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquirySiteRecord values(Integer value1, Integer value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquirySiteRecord
     */
    public InquirySiteRecord() {
        super(InquirySite.INQUIRY_SITE);
    }

    /**
     * Create a detached, initialised InquirySiteRecord
     */
    public InquirySiteRecord(Integer inquiryId, Integer siteId, Timestamp retrievedAt) {
        super(InquirySite.INQUIRY_SITE);

        set(0, inquiryId);
        set(1, siteId);
        set(2, retrievedAt);
    }
}
