/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.tables.ProjectSite;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectSiteRecord extends UpdatableRecordImpl<ProjectSiteRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -194473500;

    /**
     * Setter for <code>samply.project_site.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.project_site.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.project_site.site_id</code>.
     */
    public void setSiteId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.project_site.site_id</code>.
     */
    public Integer getSiteId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProjectSite.PROJECT_SITE.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProjectSite.PROJECT_SITE.SITE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSiteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectSiteRecord value1(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectSiteRecord value2(Integer value) {
        setSiteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectSiteRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectSiteRecord
     */
    public ProjectSiteRecord() {
        super(ProjectSite.PROJECT_SITE);
    }

    /**
     * Create a detached, initialised ProjectSiteRecord
     */
    public ProjectSiteRecord(Integer projectId, Integer siteId) {
        super(ProjectSite.PROJECT_SITE);

        set(0, projectId);
        set(1, siteId);
    }
}
