/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.tables.Tokenrequest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenrequestRecord extends UpdatableRecordImpl<TokenrequestRecord> implements Record4<Integer, Timestamp, String, String> {

    private static final long serialVersionUID = 1437081475;

    /**
     * Setter for <code>samply.tokenrequest.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.tokenrequest.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.tokenrequest.issued</code>.
     */
    public void setIssued(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.tokenrequest.issued</code>.
     */
    public Timestamp getIssued() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>samply.tokenrequest.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.tokenrequest.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>samply.tokenrequest.authcode</code>.
     */
    public void setAuthcode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.tokenrequest.authcode</code>.
     */
    public String getAuthcode() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tokenrequest.TOKENREQUEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Tokenrequest.TOKENREQUEST.ISSUED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tokenrequest.TOKENREQUEST.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tokenrequest.TOKENREQUEST.AUTHCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getIssued();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAuthcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenrequestRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenrequestRecord value2(Timestamp value) {
        setIssued(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenrequestRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenrequestRecord value4(String value) {
        setAuthcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenrequestRecord values(Integer value1, Timestamp value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenrequestRecord
     */
    public TokenrequestRecord() {
        super(Tokenrequest.TOKENREQUEST);
    }

    /**
     * Create a detached, initialised TokenrequestRecord
     */
    public TokenrequestRecord(Integer id, Timestamp issued, String email, String authcode) {
        super(Tokenrequest.TOKENREQUEST);

        set(0, id);
        set(1, issued);
        set(2, email);
        set(3, authcode);
    }
}
