/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.records;


import de.samply.share.broker.model.db.tables.UserConsent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConsentRecord extends UpdatableRecordImpl<UserConsentRecord> implements Record4<Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -761559827;

    /**
     * Setter for <code>samply.user_consent.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.user_consent.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.user_consent.consent_id</code>.
     */
    public void setConsentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.user_consent.consent_id</code>.
     */
    public Integer getConsentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.user_consent.granted</code>.
     */
    public void setGranted(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.user_consent.granted</code>.
     */
    public Timestamp getGranted() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>samply.user_consent.revoked</code>.
     */
    public void setRevoked(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.user_consent.revoked</code>.
     */
    public Timestamp getRevoked() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserConsent.USER_CONSENT.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserConsent.USER_CONSENT.CONSENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserConsent.USER_CONSENT.GRANTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return UserConsent.USER_CONSENT.REVOKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getConsentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getGranted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getRevoked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserConsentRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserConsentRecord value2(Integer value) {
        setConsentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserConsentRecord value3(Timestamp value) {
        setGranted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserConsentRecord value4(Timestamp value) {
        setRevoked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserConsentRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserConsentRecord
     */
    public UserConsentRecord() {
        super(UserConsent.USER_CONSENT);
    }

    /**
     * Create a detached, initialised UserConsentRecord
     */
    public UserConsentRecord(Integer userId, Integer consentId, Timestamp granted, Timestamp revoked) {
        super(UserConsent.USER_CONSENT);

        set(0, userId);
        set(1, consentId);
        set(2, granted);
        set(3, revoked);
    }
}
