/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.routines;


import de.samply.share.broker.model.db.Samply;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppnrInsert extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 178868686;

    /**
     * The parameter <code>samply.appnr_insert.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false, false);

    /**
     * Create a new routine call instance
     */
    public AppnrInsert() {
        super("appnr_insert", Samply.SAMPLY, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

        setReturnParameter(RETURN_VALUE);
    }
}
