/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.routines;


import de.samply.share.broker.model.db.Samply;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getnextappnr extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = -1984465654;

    /**
     * The parameter <code>samply.getnextappnr.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Getnextappnr() {
        super("getnextappnr", Samply.SAMPLY, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
    }
}
