/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankSite implements Serializable {

    private static final long serialVersionUID = 125703948;

    private Integer bankId;
    private Integer siteId;
    private Boolean approved;

    public BankSite() {}

    public BankSite(BankSite value) {
        this.bankId = value.bankId;
        this.siteId = value.siteId;
        this.approved = value.approved;
    }

    public BankSite(
        Integer bankId,
        Integer siteId,
        Boolean approved
    ) {
        this.bankId = bankId;
        this.siteId = siteId;
        this.approved = approved;
    }

    public Integer getBankId() {
        return this.bankId;
    }

    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BankSite (");

        sb.append(bankId);
        sb.append(", ").append(siteId);
        sb.append(", ").append(approved);

        sb.append(")");
        return sb.toString();
    }
}
