/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contact implements Serializable {

    private static final long serialVersionUID = -493732964;

    private Integer id;
    private byte[]  portrait;
    private String  title;
    private String  firstname;
    private String  lastname;
    private String  phone;
    private String  email;
    private String  organizationname;

    public Contact() {}

    public Contact(Contact value) {
        this.id = value.id;
        this.portrait = value.portrait;
        this.title = value.title;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.phone = value.phone;
        this.email = value.email;
        this.organizationname = value.organizationname;
    }

    public Contact(
        Integer id,
        byte[]  portrait,
        String  title,
        String  firstname,
        String  lastname,
        String  phone,
        String  email,
        String  organizationname
    ) {
        this.id = id;
        this.portrait = portrait;
        this.title = title;
        this.firstname = firstname;
        this.lastname = lastname;
        this.phone = phone;
        this.email = email;
        this.organizationname = organizationname;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public byte[] getPortrait() {
        return this.portrait;
    }

    public void setPortrait(byte... portrait) {
        this.portrait = portrait;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOrganizationname() {
        return this.organizationname;
    }

    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contact (");

        sb.append(id);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(title);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(organizationname);

        sb.append(")");
        return sb.toString();
    }
}
