/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import de.samply.share.broker.model.db.enums.DocumentType;

import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document implements Serializable {

    private static final long serialVersionUID = 237687342;

    private Integer      id;
    private Integer      projectId;
    private Integer      inquiryId;
    private Integer      userId;
    private Date         uploadedAt;
    private String       filetype;
    private String       filename;
    private byte[]       data;
    private DocumentType documentType;

    public Document() {}

    public Document(Document value) {
        this.id = value.id;
        this.projectId = value.projectId;
        this.inquiryId = value.inquiryId;
        this.userId = value.userId;
        this.uploadedAt = value.uploadedAt;
        this.filetype = value.filetype;
        this.filename = value.filename;
        this.data = value.data;
        this.documentType = value.documentType;
    }

    public Document(
        Integer      id,
        Integer      projectId,
        Integer      inquiryId,
        Integer      userId,
        Date         uploadedAt,
        String       filetype,
        String       filename,
        byte[]       data,
        DocumentType documentType
    ) {
        this.id = id;
        this.projectId = projectId;
        this.inquiryId = inquiryId;
        this.userId = userId;
        this.uploadedAt = uploadedAt;
        this.filetype = filetype;
        this.filename = filename;
        this.data = data;
        this.documentType = documentType;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public Integer getInquiryId() {
        return this.inquiryId;
    }

    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getUploadedAt() {
        return this.uploadedAt;
    }

    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    public String getFiletype() {
        return this.filetype;
    }

    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte... data) {
        this.data = data;
    }

    public DocumentType getDocumentType() {
        return this.documentType;
    }

    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(id);
        sb.append(", ").append(projectId);
        sb.append(", ").append(inquiryId);
        sb.append(", ").append(userId);
        sb.append(", ").append(uploadedAt);
        sb.append(", ").append(filetype);
        sb.append(", ").append(filename);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(documentType);

        sb.append(")");
        return sb.toString();
    }
}
