/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailSite implements Serializable {

    private static final long serialVersionUID = 1261063444;

    private Integer id;
    private String  email;
    private Integer site;

    public EmailSite() {}

    public EmailSite(EmailSite value) {
        this.id = value.id;
        this.email = value.email;
        this.site = value.site;
    }

    public EmailSite(
        Integer id,
        String  email,
        Integer site
    ) {
        this.id = id;
        this.email = email;
        this.site = site;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getSite() {
        return this.site;
    }

    public void setSite(Integer site) {
        this.site = site;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EmailSite (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(site);

        sb.append(")");
        return sb.toString();
    }
}
