/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquirySite implements Serializable {

    private static final long serialVersionUID = 2110734367;

    private Integer   inquiryId;
    private Integer   siteId;
    private Timestamp retrievedAt;

    public InquirySite() {}

    public InquirySite(InquirySite value) {
        this.inquiryId = value.inquiryId;
        this.siteId = value.siteId;
        this.retrievedAt = value.retrievedAt;
    }

    public InquirySite(
        Integer   inquiryId,
        Integer   siteId,
        Timestamp retrievedAt
    ) {
        this.inquiryId = inquiryId;
        this.siteId = siteId;
        this.retrievedAt = retrievedAt;
    }

    public Integer getInquiryId() {
        return this.inquiryId;
    }

    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Timestamp getRetrievedAt() {
        return this.retrievedAt;
    }

    public void setRetrievedAt(Timestamp retrievedAt) {
        this.retrievedAt = retrievedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquirySite (");

        sb.append(inquiryId);
        sb.append(", ").append(siteId);
        sb.append(", ").append(retrievedAt);

        sb.append(")");
        return sb.toString();
    }
}
