/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import de.samply.share.broker.model.db.enums.InquiryStatus;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inquiry implements Serializable {

    private static final long serialVersionUID = -2035630761;

    private Integer       id;
    private Integer       projectId;
    private String        label;
    private String        description;
    private Timestamp     created;
    private Date          expires;
    private Integer       authorId;
    private Boolean       archived;
    private String        criteria;
    private String        viewfields;
    private InquiryStatus status;
    private Integer       revision;
    private String        resultType;

    public Inquiry() {}

    public Inquiry(Inquiry value) {
        this.id = value.id;
        this.projectId = value.projectId;
        this.label = value.label;
        this.description = value.description;
        this.created = value.created;
        this.expires = value.expires;
        this.authorId = value.authorId;
        this.archived = value.archived;
        this.criteria = value.criteria;
        this.viewfields = value.viewfields;
        this.status = value.status;
        this.revision = value.revision;
        this.resultType = value.resultType;
    }

    public Inquiry(
        Integer       id,
        Integer       projectId,
        String        label,
        String        description,
        Timestamp     created,
        Date          expires,
        Integer       authorId,
        Boolean       archived,
        String        criteria,
        String        viewfields,
        InquiryStatus status,
        Integer       revision,
        String        resultType
    ) {
        this.id = id;
        this.projectId = projectId;
        this.label = label;
        this.description = description;
        this.created = created;
        this.expires = expires;
        this.authorId = authorId;
        this.archived = archived;
        this.criteria = criteria;
        this.viewfields = viewfields;
        this.status = status;
        this.revision = revision;
        this.resultType = resultType;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Date getExpires() {
        return this.expires;
    }

    public void setExpires(Date expires) {
        this.expires = expires;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public Boolean getArchived() {
        return this.archived;
    }

    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

    public String getCriteria() {
        return this.criteria;
    }

    public void setCriteria(String criteria) {
        this.criteria = criteria;
    }

    public String getViewfields() {
        return this.viewfields;
    }

    public void setViewfields(String viewfields) {
        this.viewfields = viewfields;
    }

    public InquiryStatus getStatus() {
        return this.status;
    }

    public void setStatus(InquiryStatus status) {
        this.status = status;
    }

    public Integer getRevision() {
        return this.revision;
    }

    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    public String getResultType() {
        return this.resultType;
    }

    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Inquiry (");

        sb.append(id);
        sb.append(", ").append(projectId);
        sb.append(", ").append(label);
        sb.append(", ").append(description);
        sb.append(", ").append(created);
        sb.append(", ").append(expires);
        sb.append(", ").append(authorId);
        sb.append(", ").append(archived);
        sb.append(", ").append(criteria);
        sb.append(", ").append(viewfields);
        sb.append(", ").append(status);
        sb.append(", ").append(revision);
        sb.append(", ").append(resultType);

        sb.append(")");
        return sb.toString();
    }
}
