/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectSite implements Serializable {

    private static final long serialVersionUID = 1980623806;

    private Integer projectId;
    private Integer siteId;

    public ProjectSite() {}

    public ProjectSite(ProjectSite value) {
        this.projectId = value.projectId;
        this.siteId = value.siteId;
    }

    public ProjectSite(
        Integer projectId,
        Integer siteId
    ) {
        this.projectId = projectId;
        this.siteId = siteId;
    }

    public Integer getProjectId() {
        return this.projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProjectSite (");

        sb.append(projectId);
        sb.append(", ").append(siteId);

        sb.append(")");
        return sb.toString();
    }
}
