/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Site implements Serializable {

    private static final long serialVersionUID = 1223935682;

    private Integer id;
    private String  name;
    private String  nameExtended;
    private String  description;
    private String  contact;

    public Site() {}

    public Site(Site value) {
        this.id = value.id;
        this.name = value.name;
        this.nameExtended = value.nameExtended;
        this.description = value.description;
        this.contact = value.contact;
    }

    public Site(
        Integer id,
        String  name,
        String  nameExtended,
        String  description,
        String  contact
    ) {
        this.id = id;
        this.name = name;
        this.nameExtended = nameExtended;
        this.description = description;
        this.contact = contact;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNameExtended() {
        return this.nameExtended;
    }

    public void setNameExtended(String nameExtended) {
        this.nameExtended = nameExtended;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Site (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(nameExtended);
        sb.append(", ").append(description);
        sb.append(", ").append(contact);

        sb.append(")");
        return sb.toString();
    }
}
