/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tokenrequest implements Serializable {

    private static final long serialVersionUID = 673476463;

    private Integer   id;
    private Timestamp issued;
    private String    email;
    private String    authcode;

    public Tokenrequest() {}

    public Tokenrequest(Tokenrequest value) {
        this.id = value.id;
        this.issued = value.issued;
        this.email = value.email;
        this.authcode = value.authcode;
    }

    public Tokenrequest(
        Integer   id,
        Timestamp issued,
        String    email,
        String    authcode
    ) {
        this.id = id;
        this.issued = issued;
        this.email = email;
        this.authcode = authcode;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Timestamp getIssued() {
        return this.issued;
    }

    public void setIssued(Timestamp issued) {
        this.issued = issued;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAuthcode() {
        return this.authcode;
    }

    public void setAuthcode(String authcode) {
        this.authcode = authcode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tokenrequest (");

        sb.append(id);
        sb.append(", ").append(issued);
        sb.append(", ").append(email);
        sb.append(", ").append(authcode);

        sb.append(")");
        return sb.toString();
    }
}
