/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSite implements Serializable {

    private static final long serialVersionUID = -919205253;

    private Integer userId;
    private Integer siteId;
    private Boolean approved;

    public UserSite() {}

    public UserSite(UserSite value) {
        this.userId = value.userId;
        this.siteId = value.siteId;
        this.approved = value.approved;
    }

    public UserSite(
        Integer userId,
        Integer siteId,
        Boolean approved
    ) {
        this.userId = userId;
        this.siteId = siteId;
        this.approved = approved;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSite (");

        sb.append(userId);
        sb.append(", ").append(siteId);
        sb.append(", ").append(approved);

        sb.append(")");
        return sb.toString();
    }
}
