/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConsent implements Serializable {

    private static final long serialVersionUID = -1015634482;

    private Integer   userId;
    private Integer   consentId;
    private Timestamp granted;
    private Timestamp revoked;

    public UserConsent() {}

    public UserConsent(UserConsent value) {
        this.userId = value.userId;
        this.consentId = value.consentId;
        this.granted = value.granted;
        this.revoked = value.revoked;
    }

    public UserConsent(
        Integer   userId,
        Integer   consentId,
        Timestamp granted,
        Timestamp revoked
    ) {
        this.userId = userId;
        this.consentId = consentId;
        this.granted = granted;
        this.revoked = revoked;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getConsentId() {
        return this.consentId;
    }

    public void setConsentId(Integer consentId) {
        this.consentId = consentId;
    }

    public Timestamp getGranted() {
        return this.granted;
    }

    public void setGranted(Timestamp granted) {
        this.granted = granted;
    }

    public Timestamp getRevoked() {
        return this.revoked;
    }

    public void setRevoked(Timestamp revoked) {
        this.revoked = revoked;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserConsent (");

        sb.append(userId);
        sb.append(", ").append(consentId);
        sb.append(", ").append(granted);
        sb.append(", ").append(revoked);

        sb.append(")");
        return sb.toString();
    }
}
