/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.BankSite;
import de.samply.share.broker.model.db.tables.records.BankSiteRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankSiteDao extends DAOImpl<BankSiteRecord, de.samply.share.broker.model.db.tables.pojos.BankSite, Record2<Integer, Integer>> {

    /**
     * Create a new BankSiteDao without any configuration
     */
    public BankSiteDao() {
        super(BankSite.BANK_SITE, de.samply.share.broker.model.db.tables.pojos.BankSite.class);
    }

    /**
     * Create a new BankSiteDao with an attached configuration
     */
    public BankSiteDao(Configuration configuration) {
        super(BankSite.BANK_SITE, de.samply.share.broker.model.db.tables.pojos.BankSite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(de.samply.share.broker.model.db.tables.pojos.BankSite object) {
        return compositeKeyRecord(object.getBankId(), object.getSiteId());
    }

    /**
     * Fetch records that have <code>bank_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.BankSite> fetchByBankId(Integer... values) {
        return fetch(BankSite.BANK_SITE.BANK_ID, values);
    }

    /**
     * Fetch records that have <code>site_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.BankSite> fetchBySiteId(Integer... values) {
        return fetch(BankSite.BANK_SITE.SITE_ID, values);
    }

    /**
     * Fetch records that have <code>approved IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.BankSite> fetchByApproved(Boolean... values) {
        return fetch(BankSite.BANK_SITE.APPROVED, values);
    }
}
