/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.Bank;
import de.samply.share.broker.model.db.tables.records.BankRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankDao extends DAOImpl<BankRecord, de.samply.share.broker.model.db.tables.pojos.Bank, Integer> {

    /**
     * Create a new BankDao without any configuration
     */
    public BankDao() {
        super(Bank.BANK, de.samply.share.broker.model.db.tables.pojos.Bank.class);
    }

    /**
     * Create a new BankDao with an attached configuration
     */
    public BankDao(Configuration configuration) {
        super(Bank.BANK, de.samply.share.broker.model.db.tables.pojos.Bank.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.broker.model.db.tables.pojos.Bank object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Bank> fetchById(Integer... values) {
        return fetch(Bank.BANK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.broker.model.db.tables.pojos.Bank fetchOneById(Integer value) {
        return fetchOne(Bank.BANK.ID, value);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Bank> fetchByEmail(String... values) {
        return fetch(Bank.BANK.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public de.samply.share.broker.model.db.tables.pojos.Bank fetchOneByEmail(String value) {
        return fetchOne(Bank.BANK.EMAIL, value);
    }

    /**
     * Fetch records that have <code>authtoken_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Bank> fetchByAuthtokenId(Integer... values) {
        return fetch(Bank.BANK.AUTHTOKEN_ID, values);
    }

    /**
     * Fetch records that have <code>clientinfo IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Bank> fetchByClientinfo(String... values) {
        return fetch(Bank.BANK.CLIENTINFO, values);
    }
}
