/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.Contact;
import de.samply.share.broker.model.db.tables.records.ContactRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContactDao extends DAOImpl<ContactRecord, de.samply.share.broker.model.db.tables.pojos.Contact, Integer> {

    /**
     * Create a new ContactDao without any configuration
     */
    public ContactDao() {
        super(Contact.CONTACT, de.samply.share.broker.model.db.tables.pojos.Contact.class);
    }

    /**
     * Create a new ContactDao with an attached configuration
     */
    public ContactDao(Configuration configuration) {
        super(Contact.CONTACT, de.samply.share.broker.model.db.tables.pojos.Contact.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.broker.model.db.tables.pojos.Contact object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchById(Integer... values) {
        return fetch(Contact.CONTACT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.broker.model.db.tables.pojos.Contact fetchOneById(Integer value) {
        return fetchOne(Contact.CONTACT.ID, value);
    }

    /**
     * Fetch records that have <code>portrait IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByPortrait(byte[]... values) {
        return fetch(Contact.CONTACT.PORTRAIT, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByTitle(String... values) {
        return fetch(Contact.CONTACT.TITLE, values);
    }

    /**
     * Fetch records that have <code>firstname IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByFirstname(String... values) {
        return fetch(Contact.CONTACT.FIRSTNAME, values);
    }

    /**
     * Fetch records that have <code>lastname IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByLastname(String... values) {
        return fetch(Contact.CONTACT.LASTNAME, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByPhone(String... values) {
        return fetch(Contact.CONTACT.PHONE, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByEmail(String... values) {
        return fetch(Contact.CONTACT.EMAIL, values);
    }

    /**
     * Fetch records that have <code>organizationname IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Contact> fetchByOrganizationname(String... values) {
        return fetch(Contact.CONTACT.ORGANIZATIONNAME, values);
    }
}
