/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.InquirySite;
import de.samply.share.broker.model.db.tables.records.InquirySiteRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquirySiteDao extends DAOImpl<InquirySiteRecord, de.samply.share.broker.model.db.tables.pojos.InquirySite, Record2<Integer, Integer>> {

    /**
     * Create a new InquirySiteDao without any configuration
     */
    public InquirySiteDao() {
        super(InquirySite.INQUIRY_SITE, de.samply.share.broker.model.db.tables.pojos.InquirySite.class);
    }

    /**
     * Create a new InquirySiteDao with an attached configuration
     */
    public InquirySiteDao(Configuration configuration) {
        super(InquirySite.INQUIRY_SITE, de.samply.share.broker.model.db.tables.pojos.InquirySite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(de.samply.share.broker.model.db.tables.pojos.InquirySite object) {
        return compositeKeyRecord(object.getInquiryId(), object.getSiteId());
    }

    /**
     * Fetch records that have <code>inquiry_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.InquirySite> fetchByInquiryId(Integer... values) {
        return fetch(InquirySite.INQUIRY_SITE.INQUIRY_ID, values);
    }

    /**
     * Fetch records that have <code>site_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.InquirySite> fetchBySiteId(Integer... values) {
        return fetch(InquirySite.INQUIRY_SITE.SITE_ID, values);
    }

    /**
     * Fetch records that have <code>retrieved_at IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.InquirySite> fetchByRetrievedAt(Timestamp... values) {
        return fetch(InquirySite.INQUIRY_SITE.RETRIEVED_AT, values);
    }
}
