/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.Note;
import de.samply.share.broker.model.db.tables.records.NoteRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoteDao extends DAOImpl<NoteRecord, de.samply.share.broker.model.db.tables.pojos.Note, Integer> {

    /**
     * Create a new NoteDao without any configuration
     */
    public NoteDao() {
        super(Note.NOTE, de.samply.share.broker.model.db.tables.pojos.Note.class);
    }

    /**
     * Create a new NoteDao with an attached configuration
     */
    public NoteDao(Configuration configuration) {
        super(Note.NOTE, de.samply.share.broker.model.db.tables.pojos.Note.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.broker.model.db.tables.pojos.Note object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Note> fetchById(Integer... values) {
        return fetch(Note.NOTE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.broker.model.db.tables.pojos.Note fetchOneById(Integer value) {
        return fetchOne(Note.NOTE.ID, value);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Note> fetchByContent(String... values) {
        return fetch(Note.NOTE.CONTENT, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Note> fetchByCreated(Timestamp... values) {
        return fetch(Note.NOTE.CREATED, values);
    }

    /**
     * Fetch records that have <code>author_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Note> fetchByAuthorId(Integer... values) {
        return fetch(Note.NOTE.AUTHOR_ID, values);
    }

    /**
     * Fetch records that have <code>project_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Note> fetchByProjectId(Integer... values) {
        return fetch(Note.NOTE.PROJECT_ID, values);
    }
}
