/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.ProjectSite;
import de.samply.share.broker.model.db.tables.records.ProjectSiteRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectSiteDao extends DAOImpl<ProjectSiteRecord, de.samply.share.broker.model.db.tables.pojos.ProjectSite, Record2<Integer, Integer>> {

    /**
     * Create a new ProjectSiteDao without any configuration
     */
    public ProjectSiteDao() {
        super(ProjectSite.PROJECT_SITE, de.samply.share.broker.model.db.tables.pojos.ProjectSite.class);
    }

    /**
     * Create a new ProjectSiteDao with an attached configuration
     */
    public ProjectSiteDao(Configuration configuration) {
        super(ProjectSite.PROJECT_SITE, de.samply.share.broker.model.db.tables.pojos.ProjectSite.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(de.samply.share.broker.model.db.tables.pojos.ProjectSite object) {
        return compositeKeyRecord(object.getProjectId(), object.getSiteId());
    }

    /**
     * Fetch records that have <code>project_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.ProjectSite> fetchByProjectId(Integer... values) {
        return fetch(ProjectSite.PROJECT_SITE.PROJECT_ID, values);
    }

    /**
     * Fetch records that have <code>site_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.ProjectSite> fetchBySiteId(Integer... values) {
        return fetch(ProjectSite.PROJECT_SITE.SITE_ID, values);
    }
}
