/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.Tokenrequest;
import de.samply.share.broker.model.db.tables.records.TokenrequestRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenrequestDao extends DAOImpl<TokenrequestRecord, de.samply.share.broker.model.db.tables.pojos.Tokenrequest, Integer> {

    /**
     * Create a new TokenrequestDao without any configuration
     */
    public TokenrequestDao() {
        super(Tokenrequest.TOKENREQUEST, de.samply.share.broker.model.db.tables.pojos.Tokenrequest.class);
    }

    /**
     * Create a new TokenrequestDao with an attached configuration
     */
    public TokenrequestDao(Configuration configuration) {
        super(Tokenrequest.TOKENREQUEST, de.samply.share.broker.model.db.tables.pojos.Tokenrequest.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.broker.model.db.tables.pojos.Tokenrequest object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Tokenrequest> fetchById(Integer... values) {
        return fetch(Tokenrequest.TOKENREQUEST.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.broker.model.db.tables.pojos.Tokenrequest fetchOneById(Integer value) {
        return fetchOne(Tokenrequest.TOKENREQUEST.ID, value);
    }

    /**
     * Fetch records that have <code>issued IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Tokenrequest> fetchByIssued(Timestamp... values) {
        return fetch(Tokenrequest.TOKENREQUEST.ISSUED, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Tokenrequest> fetchByEmail(String... values) {
        return fetch(Tokenrequest.TOKENREQUEST.EMAIL, values);
    }

    /**
     * Fetch records that have <code>authcode IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.Tokenrequest> fetchByAuthcode(String... values) {
        return fetch(Tokenrequest.TOKENREQUEST.AUTHCODE, values);
    }
}
