/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db.tables.daos;


import de.samply.share.broker.model.db.tables.UserConsent;
import de.samply.share.broker.model.db.tables.records.UserConsentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConsentDao extends DAOImpl<UserConsentRecord, de.samply.share.broker.model.db.tables.pojos.UserConsent, Record2<Integer, Integer>> {

    /**
     * Create a new UserConsentDao without any configuration
     */
    public UserConsentDao() {
        super(UserConsent.USER_CONSENT, de.samply.share.broker.model.db.tables.pojos.UserConsent.class);
    }

    /**
     * Create a new UserConsentDao with an attached configuration
     */
    public UserConsentDao(Configuration configuration) {
        super(UserConsent.USER_CONSENT, de.samply.share.broker.model.db.tables.pojos.UserConsent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(de.samply.share.broker.model.db.tables.pojos.UserConsent object) {
        return compositeKeyRecord(object.getUserId(), object.getConsentId());
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.UserConsent> fetchByUserId(Integer... values) {
        return fetch(UserConsent.USER_CONSENT.USER_ID, values);
    }

    /**
     * Fetch records that have <code>consent_id IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.UserConsent> fetchByConsentId(Integer... values) {
        return fetch(UserConsent.USER_CONSENT.CONSENT_ID, values);
    }

    /**
     * Fetch records that have <code>granted IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.UserConsent> fetchByGranted(Timestamp... values) {
        return fetch(UserConsent.USER_CONSENT.GRANTED, values);
    }

    /**
     * Fetch records that have <code>revoked IN (values)</code>
     */
    public List<de.samply.share.broker.model.db.tables.pojos.UserConsent> fetchByRevoked(Timestamp... values) {
        return fetch(UserConsent.USER_CONSENT.REVOKED, values);
    }
}
