SET search_path TO samply;

CREATE TYPE ESSENTIAL_VALUE_TYPE AS ENUM (
  'STATTYPE_DATE',
  'STATTYPE_DATETIME',
  'STATTYPE_DECIMAL',
  'STATTYPE_INTEGER',
  'STATTYPE_STRING',
  'STATTYPE_PERMITTEDVALUE'
);

CREATE TYPE SIMPLE_VALUE_CONDITION AS ENUM (
  'STATCOND_EQUALS',
  'STATCOND_NOT_EQUALS',
  'STATCOND_LESS',
  'STATCOND_GREATER',
  'STATCOND_LESS_OR_EQUALS',
  'STATCOND_GREATER_OR_EQUALS',
  'STATCOND_BETWEEN'
);

CREATE TABLE "statistics_query" (
  id         SERIAL PRIMARY KEY,
  inquiryId  INTEGER,
  created    TIMESTAMP
);

CREATE TABLE "statistics_field" (
  id         SERIAL PRIMARY KEY,
  urn        TEXT,
  valueType  ESSENTIAL_VALUE_TYPE
);

CREATE TABLE "statistics_value" (
  id         SERIAL PRIMARY KEY,
  condition  SIMPLE_VALUE_CONDITION,
  value      TEXT,
  maxValue   TEXT
);

