/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db;


import de.samply.share.broker.model.db.routines.AppnrInsert;
import de.samply.share.broker.model.db.routines.Getnextappnr;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in samply
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>samply.appnr_insert</code>
     */
    public static Object appnrInsert(Configuration configuration) {
        AppnrInsert f = new AppnrInsert();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>samply.appnr_insert</code> as a field.
     */
    public static Field<Object> appnrInsert() {
        AppnrInsert f = new AppnrInsert();

        return f.asField();
    }

    /**
     * Call <code>samply.getnextappnr</code>
     */
    public static Integer getnextappnr(Configuration configuration) {
        Getnextappnr f = new Getnextappnr();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>samply.getnextappnr</code> as a field.
     */
    public static Field<Integer> getnextappnr() {
        Getnextappnr f = new Getnextappnr();

        return f.asField();
    }
}
