/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in samply
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>samply.action_id_seq</code>
     */
    public static final Sequence<Long> ACTION_ID_SEQ = new SequenceImpl<Long>("action_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.authtoken_id_seq</code>
     */
    public static final Sequence<Long> AUTHTOKEN_ID_SEQ = new SequenceImpl<Long>("authtoken_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.bank_id_seq</code>
     */
    public static final Sequence<Long> BANK_ID_SEQ = new SequenceImpl<Long>("bank_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.consent_id_seq</code>
     */
    public static final Sequence<Long> CONSENT_ID_SEQ = new SequenceImpl<Long>("consent_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.contact_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_ID_SEQ = new SequenceImpl<Long>("contact_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.document_id_seq</code>
     */
    public static final Sequence<Long> DOCUMENT_ID_SEQ = new SequenceImpl<Long>("document_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.email_site_id_seq</code>
     */
    public static final Sequence<Long> EMAIL_SITE_ID_SEQ = new SequenceImpl<Long>("email_site_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_ID_SEQ = new SequenceImpl<Long>("inquiry_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.note_id_seq</code>
     */
    public static final Sequence<Long> NOTE_ID_SEQ = new SequenceImpl<Long>("note_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.project_id_seq</code>
     */
    public static final Sequence<Long> PROJECT_ID_SEQ = new SequenceImpl<Long>("project_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.reply_id_seq</code>
     */
    public static final Sequence<Long> REPLY_ID_SEQ = new SequenceImpl<Long>("reply_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.site_id_seq</code>
     */
    public static final Sequence<Long> SITE_ID_SEQ = new SequenceImpl<Long>("site_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.tokenrequest_id_seq</code>
     */
    public static final Sequence<Long> TOKENREQUEST_ID_SEQ = new SequenceImpl<Long>("tokenrequest_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
