/*
 * This file is generated by jOOQ.
*/
package de.samply.share.broker.model.db;


import de.samply.share.broker.model.db.tables.Action;
import de.samply.share.broker.model.db.tables.Authtoken;
import de.samply.share.broker.model.db.tables.Bank;
import de.samply.share.broker.model.db.tables.BankSite;
import de.samply.share.broker.model.db.tables.Consent;
import de.samply.share.broker.model.db.tables.Contact;
import de.samply.share.broker.model.db.tables.Document;
import de.samply.share.broker.model.db.tables.EmailSite;
import de.samply.share.broker.model.db.tables.Inquiry;
import de.samply.share.broker.model.db.tables.InquirySite;
import de.samply.share.broker.model.db.tables.Note;
import de.samply.share.broker.model.db.tables.Project;
import de.samply.share.broker.model.db.tables.ProjectSite;
import de.samply.share.broker.model.db.tables.Reply;
import de.samply.share.broker.model.db.tables.Site;
import de.samply.share.broker.model.db.tables.Tokenrequest;
import de.samply.share.broker.model.db.tables.User;
import de.samply.share.broker.model.db.tables.UserConsent;
import de.samply.share.broker.model.db.tables.UserSite;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in samply
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>samply.action</code>.
     */
    public static final Action ACTION = de.samply.share.broker.model.db.tables.Action.ACTION;

    /**
     * The table <code>samply.authtoken</code>.
     */
    public static final Authtoken AUTHTOKEN = de.samply.share.broker.model.db.tables.Authtoken.AUTHTOKEN;

    /**
     * The table <code>samply.bank</code>.
     */
    public static final Bank BANK = de.samply.share.broker.model.db.tables.Bank.BANK;

    /**
     * The table <code>samply.bank_site</code>.
     */
    public static final BankSite BANK_SITE = de.samply.share.broker.model.db.tables.BankSite.BANK_SITE;

    /**
     * The table <code>samply.consent</code>.
     */
    public static final Consent CONSENT = de.samply.share.broker.model.db.tables.Consent.CONSENT;

    /**
     * The table <code>samply.contact</code>.
     */
    public static final Contact CONTACT = de.samply.share.broker.model.db.tables.Contact.CONTACT;

    /**
     * The table <code>samply.document</code>.
     */
    public static final Document DOCUMENT = de.samply.share.broker.model.db.tables.Document.DOCUMENT;

    /**
     * The table <code>samply.email_site</code>.
     */
    public static final EmailSite EMAIL_SITE = de.samply.share.broker.model.db.tables.EmailSite.EMAIL_SITE;

    /**
     * The table <code>samply.inquiry</code>.
     */
    public static final Inquiry INQUIRY = de.samply.share.broker.model.db.tables.Inquiry.INQUIRY;

    /**
     * The table <code>samply.inquiry_site</code>.
     */
    public static final InquirySite INQUIRY_SITE = de.samply.share.broker.model.db.tables.InquirySite.INQUIRY_SITE;

    /**
     * The table <code>samply.note</code>.
     */
    public static final Note NOTE = de.samply.share.broker.model.db.tables.Note.NOTE;

    /**
     * The table <code>samply.project</code>.
     */
    public static final Project PROJECT = de.samply.share.broker.model.db.tables.Project.PROJECT;

    /**
     * The table <code>samply.project_site</code>.
     */
    public static final ProjectSite PROJECT_SITE = de.samply.share.broker.model.db.tables.ProjectSite.PROJECT_SITE;

    /**
     * The table <code>samply.reply</code>.
     */
    public static final Reply REPLY = de.samply.share.broker.model.db.tables.Reply.REPLY;

    /**
     * The table <code>samply.site</code>.
     */
    public static final Site SITE = de.samply.share.broker.model.db.tables.Site.SITE;

    /**
     * The table <code>samply.tokenrequest</code>.
     */
    public static final Tokenrequest TOKENREQUEST = de.samply.share.broker.model.db.tables.Tokenrequest.TOKENREQUEST;

    /**
     * The table <code>samply.user</code>.
     */
    public static final User USER = de.samply.share.broker.model.db.tables.User.USER;

    /**
     * The table <code>samply.user_consent</code>.
     */
    public static final UserConsent USER_CONSENT = de.samply.share.broker.model.db.tables.UserConsent.USER_CONSENT;

    /**
     * The table <code>samply.user_site</code>.
     */
    public static final UserSite USER_SITE = de.samply.share.broker.model.db.tables.UserSite.USER_SITE;
}
